from __future__ import annotations

import json
from datetime import date, timedelta
from pathlib import Path


def _seed(db: Path):
    from ktalk_mcp.registry import Registry

    with Registry(db) as reg:
        reg.upsert_recording(
            {"recording_id": "a", "name": "Standup", "date": "2026-06-24",
             "duration_min": 30},
            participants=[{"ktalk_id": "668", "name": "Демьянов Максим"}],
            now="2026-06-24",
        )
        reg.upsert_recording(
            {"recording_id": "b", "name": "1-1", "date": "2026-06-20"},
            now="2026-06-20",
        )
        reg.set_status("b", "done")


def test_list_json(tmp_path, capsys):
    from ktalk_mcp.cli import main

    db = tmp_path / "r.db"
    _seed(db)
    rc = main(["--db", str(db), "list", "--json"])
    assert rc == 0
    out = json.loads(capsys.readouterr().out)
    ids = [r["recording_id"] for r in out["recordings"]]
    assert ids == ["a", "b"]  # date DESC


def test_list_status_filter_json(tmp_path, capsys):
    from ktalk_mcp.cli import main

    db = tmp_path / "r.db"
    _seed(db)
    rc = main(["--db", str(db), "list", "--status", "new", "--json"])
    assert rc == 0
    out = json.loads(capsys.readouterr().out)
    assert [r["recording_id"] for r in out["recordings"]] == ["a"]


def test_show_json_includes_participants(tmp_path, capsys):
    from ktalk_mcp.cli import main

    db = tmp_path / "r.db"
    _seed(db)
    rc = main(["--db", str(db), "show", "a", "--json"])
    assert rc == 0
    out = json.loads(capsys.readouterr().out)
    assert out["recording_id"] == "a"
    assert out["participants"][0]["ktalk_id"] == "668"


def test_show_missing_returns_error(tmp_path, capsys):
    from ktalk_mcp.cli import main

    db = tmp_path / "r.db"
    _seed(db)
    rc = main(["--db", str(db), "show", "nope", "--json"])
    assert rc == 1
    assert capsys.readouterr().err  # non-empty stderr


def test_list_text_output(tmp_path, capsys):
    from ktalk_mcp.cli import main

    db = tmp_path / "r.db"
    _seed(db)
    rc = main(["--db", str(db), "list"])
    assert rc == 0
    out = capsys.readouterr().out
    assert "Standup" in out


def test_mark_done_updates_db(tmp_path):
    from ktalk_mcp.cli import main
    from ktalk_mcp.registry import Registry

    db = tmp_path / "r.db"
    _seed(db)
    rc = main([
        "--db", str(db), "mark-done", "a",
        "--transcript", "t.md", "--protocol", "p.md", "--type", "standup",
    ])
    assert rc == 0
    with Registry(db) as reg:
        row = reg.get_recording("a")
        assert row["status"] == "done"
        assert row["transcript_path"] == "t.md"
        assert row["meeting_type"] == "standup"


def test_mark_processing_then_partial(tmp_path):
    from ktalk_mcp.cli import main
    from ktalk_mcp.registry import Registry

    db = tmp_path / "r.db"
    _seed(db)
    assert main(["--db", str(db), "mark-processing", "a"]) == 0
    assert main(["--db", str(db), "mark-partial", "a", "--transcript", "t.md"]) == 0
    with Registry(db) as reg:
        assert reg.get_recording("a")["status"] == "partial"


def test_mark_done_missing_id_errors(tmp_path, capsys):
    from ktalk_mcp.cli import main

    db = tmp_path / "r.db"
    _seed(db)
    rc = main(["--db", str(db), "mark-done", "nope", "--transcript", "t", "--protocol", "p"])
    assert rc == 1
    assert capsys.readouterr().err


def test_set_vault_id(tmp_path):
    from ktalk_mcp.cli import main
    from ktalk_mcp.registry import Registry

    db = tmp_path / "r.db"
    _seed(db)
    rc = main(["--db", str(db), "set-vault-id", "a", "668", "mdemyanov"])
    assert rc == 0
    with Registry(db) as reg:
        assert reg.get_participants("a")[0]["vault_id"] == "mdemyanov"


def test_dashboard_json(tmp_path, capsys):
    from ktalk_mcp.cli import main

    db = tmp_path / "r.db"
    _seed(db)
    rc = main(["--db", str(db), "dashboard", "--json"])
    assert rc == 0
    out = json.loads(capsys.readouterr().out)
    assert [r["recording_id"] for r in out["new"]] == ["a"]
    assert out["stats"]["new"] == 1
    assert out["stats"]["done"] == 1


def test_export_writes_mirror(tmp_path, capsys):
    from ktalk_mcp.cli import main

    db = tmp_path / "r.db"
    _seed(db)
    out_path = tmp_path / "registry.md"
    rc = main(["--db", str(db), "export", "--out", str(out_path)])
    assert rc == 0
    text = out_path.read_text(encoding="utf-8")
    assert text.startswith("<!-- GENERATED by ktalk export")
    assert "a" in text


def test_migrate_dry_run_json(tmp_path, capsys):
    from ktalk_mcp.cli import main

    vault = tmp_path / "vault"
    tdir = vault / "95_TRANSCRIPTS"
    tdir.mkdir(parents=True)
    fixtures = Path(__file__).parent / "fixtures"
    (tdir / "registry.md").write_text(
        (fixtures / "registry.md").read_text(encoding="utf-8"), encoding="utf-8"
    )
    db = tmp_path / "r.db"
    rc = main(["--db", str(db), "migrate", str(vault), "--dry-run", "--json"])
    assert rc == 0
    out = json.loads(capsys.readouterr().out)
    assert out["recordings"] == 2
    from ktalk_mcp.registry import Registry

    with Registry(db) as reg:
        assert reg.list_recordings() == []  # dry-run wrote nothing


def test_sync_inserts_dedups_and_expires(tmp_path, capsys, monkeypatch, httpx_mock):
    monkeypatch.setenv("KTALK_BASE_URL", "https://test.ktalk.ru")
    monkeypatch.setenv("KTALK_SESSION_TOKEN", "tok")
    # Изоляция от ADR-003: KTALK_PERSONAL_API_KEY теперь тоже читается Settings и
    # побеждает по приоритету — тест должен оставаться session-режимным независимо
    # от окружения, в котором запускается (напр. реальный ключ, оставленный зондом).
    monkeypatch.delenv("KTALK_PERSONAL_API_KEY", raising=False)
    monkeypatch.delenv("KTALK_REGISTRY_DB", raising=False)

    db = tmp_path / "r.db"
    # Dates are relative to today: expiry compares against date.today(), so hardcoded
    # fixtures rot — a "fresh" recording eventually drifts past the --days window.
    today = date.today()
    yesterday = (today - timedelta(days=1)).isoformat()
    long_ago = (today - timedelta(days=200)).isoformat()

    # Pre-seed an old 'new' recording that must expire, plus one that will be re-synced.
    from ktalk_mcp.registry import Registry

    with Registry(db) as reg:
        reg.upsert_recording(
            {"recording_id": "old", "name": "Old", "date": long_ago},
            now=long_ago,
        )
        reg.upsert_recording(
            {"recording_id": "dup", "name": "Existing", "date": yesterday},
            now=yesterday,
        )
        reg.set_status("dup", "done")

    # API returns a brand-new recording plus the already-known 'dup'.
    httpx_mock.add_response(
        json={
            "recordings": [
                {"id": "fresh", "title": "Fresh", "createdDate": f"{today.isoformat()}T10:00:00Z",
                 "duration": 1800,
                 "participants": [{"userInfo": {"key": "668", "surname": "Демьянов",
                                                "firstname": "Максим"}}]},
                {"id": "dup", "title": "Existing renamed",
                 "createdDate": f"{yesterday}T10:00:00Z", "duration": 600},
            ]
        }
    )
    # FR-14 AC-2 (ADR-003/pagination.py): пагинация продолжается до ПУСТОЙ страницы
    # буквально по тексту требования, не до "короткой" — не полагаемся на признак
    # полноты, которого может не быть в ответе. Одна короткая (2 записи) непустая
    # страница поэтому не последняя сама по себе — нужна завершающая пустая.
    httpx_mock.add_response(json={"recordings": []})

    from ktalk_mcp.cli import main

    rc = main(["--db", str(db), "sync", "--days", "7", "--json"])
    assert rc == 0
    out = json.loads(capsys.readouterr().out)
    assert out["expired"] == ["old"]
    assert out["inserted"] == 1
    assert out["updated"] == 1

    with Registry(db) as reg:
        assert reg.get_recording("fresh")["status"] == "new"
        assert reg.get_recording("dup")["status"] == "done"  # status preserved
        assert reg.get_recording("dup")["name"] == "Existing renamed"  # content updated
        assert reg.get_recording("old")["status"] == "skipped"
        assert reg.get_meta("sync_count") == "1"


def test_version_flag(capsys):
    from ktalk_mcp.cli import main

    code = main(["--version"])
    out = capsys.readouterr().out
    assert code == 0
    assert out.startswith("ktalk-mcp ")
    assert out.split()[1].count(".") == 2


def test_version_matches_pyproject(capsys):
    """`ktalk --version` — источник истины для гейта совместимости плагина
    (`installed_version()` в ktalk-onboard.sh). В 0.8.0 литерал `__version__`
    остался на 0.7.0 при дистрибутиве 0.8.0, и гейт браковал совместимую
    установку. Тест ловит расхождение до релиза, а не после."""
    import tomllib
    from pathlib import Path

    from ktalk_mcp.cli import main

    pyproject = Path(__file__).resolve().parent.parent / "pyproject.toml"
    declared = tomllib.loads(pyproject.read_text(encoding="utf-8"))["project"]["version"]

    code = main(["--version"])
    printed = capsys.readouterr().out.split()[1]

    assert code == 0
    assert printed == declared, f"ktalk --version={printed}, pyproject={declared}"
